from typing import Protocol, Self

from hey.domain.entities.chat import ChatMessage, ChatSession, ChatSessionID
from hey.domain.entities.llm import LLMMessage
from hey.domain.entities.project import ProjectID


class IChatRepository(Protocol):
    def create_session(self, project_id: ProjectID) -> ChatSession: ...
    def create_message(self, session_id: ChatSessionID, message: LLMMessage) -> ChatMessage: ...
    def get_session_by_id(self, session_id: ChatSessionID) -> ChatSession | None: ...
    def save_message(self, message: ChatMessage) -> None: ...
    def get_messages_by_session_id(self, session_id: ChatSessionID) -> list[ChatMessage]: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type, exc_val, exc_tb) -> None: ...
