name: CI

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  tests:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        python-version:
          - '3.10'
          - '3.11'

    steps:
    - uses: actions/checkout@v4

    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - uses: actions/cache@v4
      name: Setup uv cache
      with:
        path: .venv
        key: ${{ runner.os }}-uv-store-${{ hashFiles('**/uv.lock') }}
        restore-keys: |
          ${{ runner.os }}-uv-store-

    - name: Install dependencies
      run: uv sync --all-extras

    - name: Lint with pysen
      run: make lint

    - name: Test with pytest
      run: make test
